"""Core data models for the trading agent."""

from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ── Enums ──────────────────────────────────────────────

class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    LIMIT = "LIMIT"
    MARKET = "MARKET"  # Implemented as aggressive limit on CLOB


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    OPEN = "OPEN"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class StrategyType(str, Enum):
    ARBITRAGE = "arbitrage"
    SENTIMENT = "sentiment"
    MARKET_MAKING = "market_making"
    EVENT_PROBABILITY = "event_probability"


class MarketOutcome(str, Enum):
    YES = "YES"
    NO = "NO"


# ── Market Data ────────────────────────────────────────

class Market(BaseModel):
    """Polymarket market metadata."""
    condition_id: str
    question: str
    slug: str
    outcomes: list[str]
    token_ids: list[str]  # YES and NO token IDs
    end_date: str | None = None
    active: bool = True
    volume: float = 0.0
    liquidity: float = 0.0
    category: str = ""
    tags: list[str] = Field(default_factory=list)


class OrderBookLevel(BaseModel):
    price: float
    size: float


class OrderBook(BaseModel):
    """Snapshot of a market's order book."""
    market_id: str
    token_id: str
    bids: list[OrderBookLevel] = Field(default_factory=list)
    asks: list[OrderBookLevel] = Field(default_factory=list)
    timestamp: float = Field(default_factory=time.time)

    @property
    def best_bid(self) -> float | None:
        return self.bids[0].price if self.bids else None

    @property
    def best_ask(self) -> float | None:
        return self.asks[0].price if self.asks else None

    @property
    def mid_price(self) -> float | None:
        if self.best_bid and self.best_ask:
            return (self.best_bid + self.best_ask) / 2
        return None

    @property
    def spread_bps(self) -> float | None:
        if self.best_bid and self.best_ask and self.mid_price:
            return ((self.best_ask - self.best_bid) / self.mid_price) * 10_000
        return None


class PriceTick(BaseModel):
    """External price data point (e.g., from Binance)."""
    symbol: str
    price: float
    timestamp: float
    source: str


# ── Trading ────────────────────────────────────────────

class Signal(BaseModel):
    """A trading signal generated by a strategy."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    strategy: StrategyType
    market_id: str
    token_id: str
    side: Side
    outcome: MarketOutcome
    confidence: float  # 0.0 - 1.0
    edge_pct: float  # Expected edge in percent
    fair_value: float  # Strategy's estimated fair probability
    market_price: float  # Current market price
    suggested_size_usd: float
    reasoning: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)
    timestamp: float = Field(default_factory=time.time)


class Order(BaseModel):
    """An order to be placed on Polymarket."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    signal_id: str
    strategy: StrategyType
    market_id: str
    token_id: str
    side: Side
    price: float
    size: float  # In USDC
    order_type: OrderType = OrderType.LIMIT
    status: OrderStatus = OrderStatus.PENDING
    filled_size: float = 0.0
    filled_price: float = 0.0
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)
    exchange_order_id: str | None = None


class Position(BaseModel):
    """An open position."""
    market_id: str
    token_id: str
    outcome: MarketOutcome
    strategy: StrategyType
    size: float  # Number of shares
    avg_entry_price: float
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    opened_at: float = Field(default_factory=time.time)

    @property
    def market_value(self) -> float:
        return self.size * self.current_price

    @property
    def cost_basis(self) -> float:
        return self.size * self.avg_entry_price


class TradeRecord(BaseModel):
    """Completed trade record for logging."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    order_id: str
    signal_id: str
    strategy: StrategyType
    market_id: str
    market_question: str = ""
    side: Side
    outcome: MarketOutcome
    price: float
    size: float
    pnl: float = 0.0
    fees: float = 0.0
    timestamp: float = Field(default_factory=time.time)


# ── Risk ───────────────────────────────────────────────

class PortfolioSnapshot(BaseModel):
    """Current portfolio state."""
    total_capital: float
    available_capital: float
    total_exposure: float
    positions: list[Position] = Field(default_factory=list)
    daily_pnl: float = 0.0
    total_pnl: float = 0.0
    max_drawdown: float = 0.0
    sharpe_ratio: float | None = None
    win_rate: float | None = None
    total_trades: int = 0
    timestamp: float = Field(default_factory=time.time)

    @property
    def exposure_pct(self) -> float:
        if self.total_capital == 0:
            return 0
        return (self.total_exposure / self.total_capital) * 100
